### ISSUE TITLE
Default to fastest virtual device

### ISSUE THREAD

**Issue by bootstraponline** [bitrise-steplib/steps-firebase-testlab#1]
`test_devices: "athene,23,en,portrait"` is the current default. As a physical device, this represents a 5x increase in costs.

NexusLowRes is the fastest virtual device on FTL for API level >= 23. I recommend that be the default.

**Comment by trapacska** [comment]
Hey!

Thank for the feedback @bootstraponline !

It is fixed in the new step, this will be deprecated.
https://github.com/bitrise-steplib/steps-virtual-device-testing-for-android/blob/master/step.yml#L36

Please feel free to reopen if you encounter any issue with it. 🚀
