### ISSUE TITLE
Android Test Orchestrator

### ISSUE THREAD

**Issue by bootstraponline** [bitrise-steplib/steps-firebase-testlab#2]
Firebase Test Lab has added support for [Android Test Orchestrator](https://developer.android.com/training/testing/junit-runner.html#using-android-test-orchestrator). The bitrise step should both allow toggling Orchestrator on/off and always print if a run used Orchestrator or not.

Orchestrator has some known issues around broken test coverage and invalid test counts. As a result, it should default to off.

**Comment by trapacska** [comment]
This is added in the official version of the step. Thank you!

**Comment by viktorbenei** [comment]
Was added in https://github.com/bitrise-steplib/steps-virtual-device-testing-for-android
