### ISSUE TITLE
Environment

### ISSUE THREAD

**Issue by ghost** [bitrise-steplib/steps-firebase-testlab#3]
Hi,

I have a question about which values should I enter in these fields:

ADDON_FIREBASE_API_URL
ADDON_FIREBASE_API_TOKEN

These variables must in what section in the bitrise?

**Comment by trapacska** [comment]
Hey @cshalysongoncalves !

This step is now outdated, the new step that replaced this one is: https://github.com/bitrise-steplib/steps-virtual-device-testing-for-android

That two environment variables are exported at the time when a build starts, with unique api access tokens that required for communicate with our service. So to get those envs working, all you need to do is basically just to add the step I linked you above after gradle runner, and turn on Virtual Device Testing option on the app's settings page.

Closing the ticket now, as it is not an exact issue with the step itself. 

Thank you for your great question!
Feel free to contact us on our on-site chat, or on our https://discuss.bitrise.io
